analytics:
  facebook: '306997042975680'
  google: UA-57412357-1
author:
  email: welcome@christian-lautner.com
  name: Christian Lautner
  url: www.christian-lautner.com
color:
  brandColors:
    - '#EBF1FF'
    - '#B9C4CA'
    - '#800D14'
    - '#677F81'
    - '#151016'
  brandStrength: 1
  lightness: 0.788002
  rhythmicContrast: 0.824551
  saturation: 0.609583
content_rating:
  adult: false
layout_spectrum: 0
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e23cb764-5368-4332-b20a-97a01e0abcd1.jpg
name: Christian Lautner
opengraph:
  appId: '913436692099822'
title: Running Entrepreneur
typography_spectrum: 1
